//
// Created by admin on 01.03.2021.
//

#ifndef PROCESSMANAGERSERVICE_SERVICECONFIGURATION_HPP
#define PROCESSMANAGERSERVICE_SERVICECONFIGURATION_HPP

class ServiceConfiguration {};

#endif // PROCESSMANAGERSERVICE_SERVICECONFIGURATION_HPP
